rails_app/config/routes.rb
Rails.application.routes.draw do

  get 'home/index'
  root :to => 'home#index'
  
end

rails_app/app/models/address.rb
class Address < ApplicationRecord
  belongs_to :user
end

rails_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

rails_app/app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
  belongs_to :parent, foreign_key: :parent_id, class_name: 'User', inverse_of: :invitation_cards
  has_many :purchases, as: :contractable
end

rails_app/app/models/category.rb
class Category < ApplicationRecord
  has_ancestry

  has_many :user_categories
  has_many :users, through: :user_categories
  has_many :offer_categories
  has_many :offers, through: :offer_categories
end

rails_app/app/models/contract.rb
class Contract < ApplicationRecord
  belongs_to :user
  belongs_to :program
  has_many :payments
  has_many :rewards
  has_many :purchases, as: :contractable
  has_many :fees
end

rails_app/app/models/fee.rb
class Fee < ApplicationRecord
  belongs_to :contract
  has_many :rewards, as: :rewardable
end

rails_app/app/models/offer.rb
class Offer < ApplicationRecord
  belongs_to :user
  has_many :offer_categories
  has_many :categories, through: :offer_categories
  has_many :purchases
end

rails_app/app/models/offer_category.rb
class OfferCategory < ApplicationRecord
  belongs_to :offer
  belongs_to :category
end

rails_app/app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :contract
end

rails_app/app/models/program.rb
class Program < ApplicationRecord
  has_many :contracts
  has_many :program_rewards_from, class_name: 'ProgramReward', inverse_of: :program
  has_many :program_rewards_to, class_name: 'ProgramReward', inverse_of: :target_program

  def is_partner
    partner_offers_max_count > 0
  end
end

rails_app/app/models/program_reward.rb
class ProgramReward < ApplicationRecord
  belongs_to :program
  belongs_to :target_program, class_name: 'Program'
end

rails_app/app/models/purchase.rb
class Purchase < ApplicationRecord
  belongs_to :offer
  belongs_to :contractable, polymorphic: true
  belongs_to :waiter
  has_many :rewards, as: :rewardable
end

rails_app/app/models/reward.rb
class Reward < ApplicationRecord
  belongs_to :rewardable, polymorphic: true
  belongs_to :contract
end

rails_app/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_ancestry
  acts_as_avatarable
  has_many :user_categories
  has_many :categories, through: :user_categories
  has_many :contracts
  has_many :payments, through: :contracts
  has_many :offers # as partner
  has_many :invitation_cards, class_name: 'Card', inverse_of: :parent, foreign_key: :parent_id # as partner who issued the card
  has_one :card # as card owner
  has_many :waiters # as partner
  has_many :addresses

  # @return Contract
  def current_contract
    contracts.where('created_at <= ?', Time.now).order('created_at desc').first
  end

  def current_program
    current_contract.try &:program
  end

  def current_program_name
    current_program.try &:name
  end

  # Sum amounts of all direct payments
  def sum_payments
    contracts.sum{ |c| c.payments.sum(&:amount)}
  end

  # As member
  def sum_fees
    contracts.sum{ |c| c.fees.sum(&:total)}
  end

  # As member
  def balance
    sum_payments - sum_fees
  end

  def is_partner
    if current_contract
      current_contract.program.is_partner
    else
      false
    end
  end

end

rails_app/app/models/user_category.rb
class UserCategory < ApplicationRecord
  belongs_to :user
  belongs_to :category
end

rails_app/app/models/waiter.rb
class Waiter < ApplicationRecord
  belongs_to :user # partner, u koho pracuje
  has_many :purchases
end

rails_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def access_denied(exception)
    redirect_to root_path, alert: exception.message
  end

  def after_sign_in_path_for(resource)
    stored_location_for(resource) ||
      if resource.is_a?(User)
        if resource.admin
          admin_root_path
        else
          members_dashboard_index_path
        end
      else
        super
      end
  end
end

rails_app/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @users = User.all
  end
end

rails_app/app/helpers/application_helper.rb
module ApplicationHelper

  def flash_level(level)
    case level.to_sym
      when :success then 'alert-success' # Green
      when :notice then 'alert-info' # Blue
      when :error then 'alert-danger' # Red
      when :alert then 'alert-warning' # Yellow
      else level
    end
  end

end

rails_app/app/helpers/home_helper.rb
module HomeHelper
end

rails_app/app/views/home/index.html.haml
Users:
%table{border: 1}
  %tr
    %th ID
    %th First name
    %th Surname
    %th Email
    %th Parent ID
    %th Balance
  - @users.each do |user|
    %tr
      %td= user.id
      %td= user.firstname
      %td= user.surname
      %td= user.email
      %td= user.ancestry
      %td= user.balance
  

rails_app/app/views/layouts/_flash_messages.html.haml
- if flash
  - flash.each do |level, message|
    %div{:class => "alert #{flash_level(level)}"}
      %button.close{:"data-dismiss" => 'alert'}= "×"
      = message

rails_app/app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: 'text/html; charset=UTF-8', 'http-equiv' => 'Content-Type'}/
    %title Claab
    = csrf_meta_tags
    = action_cable_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track' => 'reload'
  - if @is_landing_page
    %body.flat-blue.landing-page
      = yield
  - else
    %body.flat-blue
      = render 'navigation/main'
      = render 'layouts/flash_messages'
      %div.side-body
        = yield

rails_app/app/views/navigation/_main.html.haml
%nav.navbar.navbar-inverse.navbar-static-top.navbar-affix{"data-offset-top" => "60", "data-spy" => "affix", :role => "navigation"}
  .container
    .navbar-header
      %a.navbar-brand{:href => "#"}
        .icon.fa.fa-paper-plane
        .title CLAAB
    #navbar.navbar-collapse.collapse{"aria-expanded" => "true"}
      = menu_group do
        = menu_item 'Home', home_index_path